### ISSUE TITLE
Can't deploy the package

### ISSUE THREAD

**Issue by mihin** [jsmithdev/force-rtc#3]
Hey,

can't figure out how to deploy metadata/Connect.object. All commands give me errors.

Moreover, ForceRTC.page has a "jamiesmith__Answer__c" dependency, where can I find it?

Could you please help with that?

**Comment by jsmithdev** [comment]
Answer__c is a field on the  Connection__c object. jamiesmith__ is a namespace for an old dev org of mine so jamiesmith__ needs removed wherever it's used. I'm on rapid covid projects but when I get time, I'll try to remove all namespace prefixes and deploy with sfdx (covert then deploy) to another dev org and update repo.

**Comment by mihin** [comment]
Thanks in advance and good luck with covid projects
